### ISSUE TITLE
Upload fact checks

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#672]
**Description**
Check media launched a [new  API](https://github.com/meedan/check/wiki/GraphQL-query-examples#create-fact-check) to import  fact-checks in Check.

**Solution**
Write a node js daily cron script that
- Use [RSSJson](https://api.rss2json.com/v1/api.json) to fetch uploads from Pesacheck.
- Process data as per the [documentation](https://github.com/meedan/check/wiki/GraphQL-query-examples#create-fact-check).
- Upload the content.
- Use Sentry as a mechanism for logging status updates of the uploads

**Alternatives**
- The ideal alternative would be to use a medium API  but we are limited by the fact that medium no longer supports public API.

**Additional context**
- Since RSS JSON limits us to only 10 items per request, the team mentioned that they upload 15 - 20 checks per month. Doing a daily cron getting 10 items each ensures that no item is missed.
- The API handles conflicts by returning 409 status code if similar titles are uploaded.

**Comment by koechkevin** [comment]
Your take @kilemensi

**Comment by kilemensi** [comment]
Thanks @koechkevin.

Can you clarify a bit more on "RSS JSON limits us to only 10 items per request"? e.g. can I say I want to start from a given date or it just return the latest 10 items and that's it? Meaning, if we run it now, it will return the 10 items published in Jan but nothing published from Dec (assuming PesaCheck publishes 10 articles per month).

... and why is the issue here in the UI repo? Isn't this app basically an API?

**Comment by koechkevin** [comment]
@kilemensi Sorry for replying this late, I was on a call.

The free version has a limitation of  maximum of 10 items per request. There is a parameter [`order_by` and `order_dir `](https://rss2json.com/docs) which requires API key, and we can use it to sort by pubDate, desc.

**Comment by koechkevin** [comment]
Move
